"""aderencia ao trabalho na fai

Revision ID: 4b448abc1d94
Revises: c14a7f2e9b03
Create Date: 2026-08-10 18:36:05.183442
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '4b448abc1d94'
down_revision: str | None = 'c14a7f2e9b03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_adherence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('signal', sa.Enum('organizational_adoption', 'technical_ai', 'data_and_process', 'governance', 'training', name='adherence_signal'), nullable=False),
    sa.Column('level', sa.Enum('strong', 'partial', 'absent', 'unknown', name='adherence_level'), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('verified_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['graduate_program.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'signal')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_adherence')
    # Os ENUMs NÃO caem com a tabela: o PostgreSQL os mantém, e o próximo
    # `upgrade head` morre com DuplicateObjectError ao tentar recriá-los. Já
    # aconteceu antes neste repositório — um downgrade que não desfaz de verdade
    # é pior que nenhum, porque só falha na próxima subida.
    op.execute("DROP TYPE IF EXISTS adherence_signal")
    op.execute("DROP TYPE IF EXISTS adherence_level")
    # ### end Alembic commands ###
