"""requisitos eliminatorios por programa

Revision ID: 8fb2b1dfdc68
Revises: 9a501a766570
Create Date: 2026-08-09 06:40:37.084640
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8fb2b1dfdc68'
down_revision: str | None = '9a501a766570'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('requirement', sa.Enum('evening_classes', 'in_person_sao_carlos', 'tuition_free', 'public_institution', name='requirement'), nullable=False),
    sa.Column('status', sa.Enum('met', 'not_met', 'unknown', name='requirement_status'), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('verified_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['graduate_program.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'requirement')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_requirement')
    # ### end Alembic commands ###
