"""data do resultado definitivo do ciclo

Revision ID: 9a501a766570
Revises: bd69e261c650
Create Date: 2026-08-09 06:25:32.067889
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9a501a766570'
down_revision: str | None = 'bd69e261c650'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admission_cycle', sa.Column('final_result_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admission_cycle', 'final_result_on')
    # ### end Alembic commands ###
