"""notificacoes com deduplicacao

Revision ID: 815f5ec57df7
Revises: e6319f5b4c0b
Create Date: 2026-08-10 22:05:57.715118
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '815f5ec57df7'
down_revision: str | None = 'e6319f5b4c0b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('cycle_open', 'deadline_soon', 'notice_changed', 'source_blind', 'schedule_verdict', name='notification_kind'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # O ENUM não cai com a tabela no PostgreSQL, e o próximo `upgrade head` morre
    # com DuplicateObjectError. Quarta vez que esta classe de bug aparece aqui.
    op.execute("DROP TYPE IF EXISTS notification_kind")
    # ### end Alembic commands ###
