"""snapshot text and change flag

Revision ID: bd69e261c650
Revises: ac39948ca84d
Create Date: 2026-08-09 05:36:06.915169
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'bd69e261c650'
down_revision: str | None = 'ac39948ca84d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_snapshot', sa.Column('text', sa.Text(), nullable=True))
    op.add_column('source_snapshot', sa.Column('final_url', sa.Text(), nullable=True))
    op.add_column('source_snapshot', sa.Column('content_type', sa.String(length=120), nullable=True))
    op.add_column('source_snapshot', sa.Column('changed', sa.Boolean(), nullable=False))
    op.add_column('source_snapshot', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_snapshot', 'error')
    op.drop_column('source_snapshot', 'changed')
    op.drop_column('source_snapshot', 'content_type')
    op.drop_column('source_snapshot', 'final_url')
    op.drop_column('source_snapshot', 'text')
    # ### end Alembic commands ###
