"""initial domain

Revision ID: ac39948ca84d
Revises: 
Create Date: 2026-08-09 01:50:00.494556
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'ac39948ca84d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('employer', sa.String(length=200), nullable=True),
    sa.Column('work_starts_at', sa.Time(), nullable=True),
    sa.Column('work_ends_at', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('faculty_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('affiliation_status', sa.Enum('permanent', 'collaborator', 'senior_permanent', name='affiliation_status'), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('external_affiliation', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('acronym', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acronym'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'name')
    )
    op.create_table('candidate_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=120), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'topic')
    )
    op.create_table('faculty_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('lattes', 'orcid', 'laboratory', 'personal', 'institutional', 'other', name='link_kind'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty_member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Enum('institutional_page', 'graduate_program_page', 'admission_page', 'edital_pdf', 'schedule_pdf', 'course_catalog', 'faculty_page', 'laboratory_page', 'research_group_page', 'regulation_pdf', 'lattes', 'orcid', 'news', name='source_type'), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('redirects_to', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('check_frequency', sa.String(length=30), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('acronym', sa.String(length=20), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_path', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graduate_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('acronym', sa.String(length=30), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('capes_rating', sa.Integer(), nullable=True),
    sa.Column('tuition_free', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acronym')
    )
    op.create_table('admission_cycle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('entry_mode', sa.Enum('regular', 'special_student', 'graduation_track', name='entry_mode'), nullable=False),
    sa.Column('degree_level', sa.Enum('master', 'doctorate', 'direct_doctorate', 'postdoc', name='degree_level'), nullable=True),
    sa.Column('applications_open_on', sa.Date(), nullable=True),
    sa.Column('applications_close_on', sa.Date(), nullable=True),
    sa.Column('site_label', sa.String(length=120), nullable=True),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['graduate_program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'year', 'semester', 'entry_mode')
    )
    op.create_table('discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('name_en', sa.String(length=300), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('group', sa.Enum('I', 'II', 'III', 'IV', name='discipline_group'), nullable=True),
    sa.Column('curriculum_version', sa.String(length=30), nullable=False),
    sa.Column('syllabus', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['graduate_program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'code', 'curriculum_version')
    )
    op.create_table('research_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('acronym', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['graduate_program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'acronym')
    )
    op.create_table('admission_notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['admission_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admission_seat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('research_line_id', sa.Integer(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['admission_cycle.id'], ),
    sa.ForeignKeyConstraint(['research_line_id'], ['research_line.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'research_line_id')
    )
    op.create_table('admission_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('result_on', sa.Date(), nullable=True),
    sa.Column('eliminatory', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['admission_cycle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id', 'ordinal')
    )
    op.create_table('course_offering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('scope', sa.Enum('basica', 'especifica', name='offering_scope'), nullable=True),
    sa.Column('research_line_id', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Enum('monday', 'tuesday', 'wednesday', 'thursday', 'friday', name='weekday'), nullable=True),
    sa.Column('starts_at', sa.Time(), nullable=True),
    sa.Column('ends_at', sa.Time(), nullable=True),
    sa.Column('language', sa.Enum('pt-BR', 'en', name='language'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['discipline.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty_member.id'], ),
    sa.ForeignKeyConstraint(['research_line_id'], ['research_line.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discipline_id', 'year', 'semester')
    )
    op.create_table('faculty_research_line',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('research_line_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty_member.id'], ),
    sa.ForeignKeyConstraint(['research_line_id'], ['research_line.id'], ),
    sa.PrimaryKeyConstraint('faculty_id', 'research_line_id')
    )
    op.create_table('required_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('mandatory', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['admission_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admission_notice_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('is_rectification', sa.Boolean(), nullable=False),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['admission_notice.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['source_snapshot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offering_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('campus_id', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(length=120), nullable=True),
    sa.Column('is_origin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offering.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offering_location')
    op.drop_table('admission_notice_version')
    op.drop_table('required_document')
    op.drop_table('faculty_research_line')
    op.drop_table('course_offering')
    op.drop_table('admission_stage')
    op.drop_table('admission_seat')
    op.drop_table('admission_notice')
    op.drop_table('research_line')
    op.drop_table('discipline')
    op.drop_table('admission_cycle')
    op.drop_table('graduate_program')
    op.drop_table('source_snapshot')
    op.drop_table('department')
    op.drop_table('source')
    op.drop_table('faculty_link')
    op.drop_table('candidate_interest')
    op.drop_table('campus')
    op.drop_table('institution')
    op.drop_table('faculty_member')
    op.drop_table('candidate')
    # ### end Alembic commands ###

    # Alembic's autogenerate drops TABLES but never the ENUM TYPES it created, so
    # a downgrade leaves them orphaned and the next `upgrade head` dies with
    # DuplicateObjectError. Dropping them explicitly is what makes the cycle
    # reversible — and an irreversible downgrade is not a downgrade.
    op.execute("DROP TYPE IF EXISTS affiliation_status")
    op.execute("DROP TYPE IF EXISTS degree_level")
    op.execute("DROP TYPE IF EXISTS discipline_group")
    op.execute("DROP TYPE IF EXISTS entry_mode")
    op.execute("DROP TYPE IF EXISTS language")
    op.execute("DROP TYPE IF EXISTS link_kind")
    op.execute("DROP TYPE IF EXISTS offering_scope")
    op.execute("DROP TYPE IF EXISTS source_type")
    op.execute("DROP TYPE IF EXISTS weekday")
